### ISSUE TITLE
Error in iaps_newanim

### ISSUE THREAD

**Issue by Joecorleone** [ray-hplus/inkscape-animation#1]
Running the "new animation" command resulted in the error: self.effect has no attribute unittouu, for the following lines of file iaps_newanim.py:
		docw = self.effect.unittouu( root.get("width") )
		doch = self.effect.unittouu( root.get("height") )
Replacing self.effect with inkex resolved this for me.
Maybe this helps someone else.

(This is probably the wrong place to post. No prior experience using github.)

**Comment by ray-hplus** [comment]
Hey there.
Thanks for your attention, I'll definitely look into this later: I'm
planning some updates and this might be useful.
For the github usage: please look at the 'fork' and 'pull request'
features.
Thank you again.

**Comment by b4zz4** [comment]
```
doch = inkex.unittouu(self.document.getroot().get('height'))
 docw = inkex.unittouu(self.document.getroot().get('width'))
```
I made this change

**Comment by b4zz4** [comment]
I think that the problem this here:

```
    a = AnimationExport( self, n, actual_path, make_gif, gif_rate, frame_w, frame_h, use_frame_wh, self.options.debug )
    self.geom = self.get_bg_rect_geometry()
    x = self.effect.unittouu( self.bg_rect.get('x') )
```

That version of python have to use?

**Comment by b4zz4** [comment]
wor in inkscape .91

**Comment by Joecorleone** [comment]
I can confirm this observation. In Ubuntu 14.04 the inkscape version in the standard repository is 0.41. Can be upgraded using the stable ppa: "ppa:inkscape.dev/stable". This solves the mentioned issue.
